### ISSUE TITLE
Bluetooth devices not reachable

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost-Apps/domoticz_ynh#16]
Current systemd configuration do not allow to reach bluetooth devices, even if BLE devices can be read by domoticz. 

I managed to allow this by adding `AF_BLUETOOTH` on this line:
https://github.com/YunoHost-Apps/domoticz_ynh/blob/27311ad7b8fc72fb065f60c769f21546e9b647a9/conf/systemd.service#L24

I can easily fix the problem on the repo and open a PR. Do you prefer me to change the documentation (so that users make the change themselves) or directly edit the `systemd.service` file ?

**Comment by Krakinou** [comment]
Hi!
Thanks for the help, you can make a PR to change the systemd.service to testing and I will publish it along with the next version
