### ISSUE TITLE
Domoticz authentication system requires auth_header = false

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost-Apps/domoticz_ynh#19]
### Describe the bug

Domoticz user is always disconnected after successful sign in due to a late version (11.2 or older) of ssowat.

### Context

- YunoHost version: 11.2.3
- ssowat version: 11.2
- Domoticz 2023.2 (but I don't know if it could happen with an older version)

### Steps to reproduce

- Start with a perfectly functionnal domoticz install (including user management)
- Upgrade ssowat to the latest version
- Restart nginx to load the latest version of ssowat
- when trying to sign in inside Domoticz (with valid credentials), there is an infinite loop (sign in form always displayed, even if the sign in was successful)
- Domoticz runs normally in the background (the logs show that the sensor probing works fine), but the user is locked outside the webUI.
- This will happen on all the new domoticz install on an up to date yunohost
### Bug analysis
- ssowat deletes the Domoticz session cookies (or replaces them with its own) due to `auth_header` set to `true`.

### Fix

I managed to have everything work by manually setting `auth_header` to `false` in `/etc/ssowat/conf.json` for `domoticz.main`, however, it is not persistant and it will have to be manually modified again the next time `yunohost app ssowatconf` is run.

**Comment by Krakinou** [comment]
Hello,
Thanks for reporting, I just noticed the same issue myself.
For now, you may avoid it by using anonymous browsing : it allows to connect correctly yo domoticz
For the ssowat config, you should put it in /etc/ssowat/conf.json.persistent if you want it to be persistent, althought I'm not clear on the exact syntax.

In the meantime, I will look for a longer-term fix.

**Comment by Krakinou** [comment]
Should be ok in ~ynh8

**Comment by ZeHiro** [comment]
Works very well, thank you
